# Book settings
title: Python for mathematics
author: Vincent Knight
parse:
  myst_extended_syntax: true
exclude_patterns: ["*.bcp.ipynb", "**/*.bcp.ipynb", "**/README.md"]
latex:
  latex_documents:
    targetname: book.tex
